### ISSUE TITLE
Weird output path

### ISSUE THREAD

**Issue by sebbi08** [odata2ts/odata2ts#137]
When I have a config like

```
const config: ConfigFileOptions = {
  mode: Modes.models,
  emitMode: EmitModes.dts,
  services: {
    trippin: {
      source: 'app/src/localService/metadataBP.xml',
      output: 'app/src/localService/types/metadataBP',
    },
  },
};
```

the final path of the dTs file is:

**app/src/localService/metadataBP/app/src/localService/metadataBP/BusinessPartnersServiceModel.d.ts**

Is there a way to get rid of the second app/... ?

**Comment by texttechne** [comment]
Hey @sebbi08, 
looks indeed weired. 
As this behaviour doesn't occur in the examples, I would guess this happens because of the way you use it. So please add some more information:
* From where are you starting the generation process? Ar you calling `yarn / npm odata2ts` from the root folder or from within `app/src/localService/metadataBP`?
* are you using a `script` within the `package.json`?

You can also try to use the mentioned examples: [Trippin is the standard example](https://github.com/odata2ts/odata2ts/tree/main/examples/trippin)

**Comment by sebbi08** [comment]
Hi, I am running this with `npx odata2ts` from the root folder. The config file is also at the root folder.

I have also tried putting it in a script in package.json

"gen": "odata2ts"

but has the same result

**Comment by sebbi08** [comment]
I also tried the sample there, it is working correctly.
[test.zip](https://github.com/odata2ts/odata2ts/files/10839303/test.zip)

here is a small project where the error occurs

**Comment by texttechne** [comment]
Ok, it works with `EmitMode=TS` as its supposed to work.
Hence, it should be due to the `tsconfig.json`.

Need to investigate further, but later...

**Comment by texttechne** [comment]
By the way, you can also specify a different `tsconfig.json` via the option `tsconfig`. For example:

```ts 
const config: ConfigFileOptions = {
  mode: Modes.models,
  emitMode: EmitModes.dts,
  tsconfig: "tsconfig.odata2ts.json",
  services: {...},
  },
};
````

**Comment by texttechne** [comment]
Ok, so as soon as you have the generated files (mode=js|dts|js_dts) generate to one of the folder which get included in your tsconfig.json, then this duplication of the path occurs. In your case:
```json
{
    ...
    "include": ["app/srv/**/*.ts", "app/src/**/*.ts"],
}
```

The workaround for now would be: Create a new, separate `tsconfig.json` for the generation process. You probably want to do it anyways, since you seem to use TypeScript also for the server part...

I will dig into the real problem later...

**Comment by texttechne** [comment]
Hi @sebbi08,

actually it works as configured: see [root dir description](https://www.typescriptlang.org/tsconfig#rootDir) for a better explanation than I could give.

In your case this works:
```json
{
  "compilerOptions": {
    "rootDirs": ["./app/src", "./app/srv"],
    ...
  }
}
```

So I'll regard this as closed. Please reopen if I'm mistaken here.
