### ISSUE TITLE
Support for OData V2

### ISSUE THREAD

**Issue by uxkjaer** [odata2ts/odata2ts#14]
Hello,
Found this repo after asking on twitter. I work in the SAP ecosystem and recently the official UI framework SAPUI5 is moving to typescript. Since SAPUI5 relies heavily on OData both V2 and V4, I thought this could be a great tool for helping in that journey. However when I tested it, I saw that OData V2 can't be typed currently.

Before I get working on this, I wanted to ask if you are interested in getting this support. I suppose an additional parameter in the CLI --v2 or something to indicate it's a v2 model.

**Comment by texttechne** [comment]
Hi @uxkjaer,

yeah, V2 support is not available currently. It is planned, however. That is, when I find the time for it, but we'll need this as well in the future.

If you want to work on this support, you're more than welcome.
The CLI probably doesn't need this switch you're talinkg about, since the metadata of the OData service will contain that information.

**Comment by texttechne** [comment]
Hi @uxkjaer,

v2 support for model generation has landed in master. It hasn't been released however, since there is still much to do:
* support for `Edm.DateTime` and `Edm.Time` regarding query-objects
* support for the typesafe URI-Builder
* support for the generated odata service (undocumented) which realizes a "complete" odata client (much like what cloud sdk can do), but without the axios part  

I assume that you are not interested in this stuff, but that you're only concerned with plain model generation. If that is true, then you're good to go: Call the CLI with `mode=model`.

Two remarks here, for completeness sake:

First, there are still "nominal types" present in the generated models, e.g. `Edm.DateTime` is converted to `DateTimeString` instead of  `string` => this is not necessary anymore and will be changed with #22 

Second, I've realized that the generated models are not sufficient regarding create and update actions. Although some properties are actually `required` (Nullable="false" in EDMX), they are managed on the server side, e.g. ids or something like "createdAt" or "lastModified". For example creating / updating an entity with a generated ID, we require a second interface where the id prop is not included. This information is actually not present in the metadata. => #15
