### ISSUE TITLE
Explicit property renaming does not seem to work

### ISSUE THREAD

**Issue by manuelseeger** [odata2ts/odata2ts#142]
I have the following configfileoptions: 

```
{
  allowRenaming: true,
  prettier: true, 
  mode: Modes.service,
  emitMode: EmitModes.ts,
  services: {
    cpi: {
      source: "assets/CPI$metadata.xml",
      output: "src/generated/cpi",
      propertiesByName: [
        {
          name: "FromId_",
          mappedName: "fromId_"
        }
      ]
    }
  },
}
```

But it appears the property by name setting is not applied. Source Metadata: 

```
            <EntityType Name="IdMapToId">
                <Key>
                    <PropertyRef Name="ToId" />
                </Key>
                <Property Name="ToId" Type="Edm.String" Nullable="false" />
                <Property Name="FromId_" Type="Edm.String" Nullable="true" />
                <Property Name="Mapper" Type="Edm.String" Nullable="true" />
                <Property Name="ExpirationTime" Type="Edm.DateTimeOffset" Nullable="true" />
                <Property Name="Qualifier" Type="Edm.String" Nullable="true" />
                <Property Name="Context" Type="Edm.String" Nullable="true" />
                <NavigationProperty Name="FromId" Relationship="com.sap.hci.api.ToIdsForFromId"
                    FromRole="r_ToIds" ToRole="r_FromId" />
                <NavigationProperty Name="FromId2s" Relationship="com.sap.hci.api.ToIdsForFromId2"
                    FromRole="r_ToId" ToRole="r_FromId2s" />
            </EntityType>
```

In the generated TS: 

```
export interface IdMapToId {
  toId: string;
  fromId: string | null;
  mapper: string | null;
  expirationTime: string | null;
  qualifier: string | null;
  context: string | null;
  fromId: IdMapFromId | null | DeferredContent;
  fromId2s: Array<IdMapFromId2> | DeferredContent;
}
```

(The renaming strategy produces duplicate identifiers by stripping the trailing underscore from Property "FromId_", which is why I wanted to explicitly set the name of this property)

Am I missing something?

Full metadata: https://api.sap.com/api/IntegrationContent/overview

**Comment by texttechne** [comment]
Hi, this behaviour is due to the usage of [change-case](https://github.com/blakeembrey/change-case) library which is responsible for applying the "naming strategies", i.e. camelCase or PascalCase. The character `_` actually is recognized as separator (in the same way as whitespace would act as separator).

Your current options / workarounds:
* Rename some more: "fromId_" => "fromIdPrivate"
* Don't rename entity props => set `allowRenaming` to false
  * now, all props stay as they are, i.e. with capital case in your example
  * No "namingStrategy" is applied though => undescores will survive

CAP behaves similarly, but instead of using the underscore for the separate id field, they always sufffix it with "ID".

The situation is less than ideal... maybe the underscroe deserves a different, special treatment...

**Comment by texttechne** [comment]
And the 3rd workaround: you can also use  a regular expression for the property name and replace stuff in the `mappedName`.

**Comment by manuelseeger** [comment]
So are the propertiesByName also fed through change-case? From the outside it looked more like a naive search and replace applied whether renaming is allowed or not. 

Anyway, workaround 1 works for me. Should have tried different names myself.
