### ISSUE TITLE
Axios is out of date

### ISSUE THREAD

**Issue by matbee-eth** [odata2ts/odata2ts#162]
Consider making axios a peerDependency

**Comment by texttechne** [comment]
Personally, I disagree. It's still a viable option and has some advantages over `fetch`; assuming that you hint at native libs as the modern way to go.

However, `odata2ts` is open for any HTTP client: [Read the docs!](https://odata2ts.github.io/docs/http-client/odata-client)

So the question with this issue becomes: What's the actionable task here? Do you require `fetch`?

**Comment by manuelseeger** [comment]
I wrote a fetch client for my use case since I didn't want to depend on axios anymore either. It was pretty straightforward. Only mapping responses to the HttpResponseModel (which I assume was taken from the Axis response) is a bit awkward.

**Comment by texttechne** [comment]
@manuelseeger do you want to contribute the client to the repo?

**Comment by manuelseeger** [comment]
It's not in a ready state right now but once I spend a little bit more time on the project, sure.

**Comment by texttechne** [comment]
@manuelseeger please take a look at `@odata2ts/http-client-fetch` which is the fetch implementation.
It lives in an own repository: [http-client](https://github.com/odata2ts/http-client).

Any feedback would be most welcome.

I'm moving the other implementations over to this repo and thereby renaming the modules. I will address the extensibility issue you've mentioned then.

**Comment by texttechne** [comment]
@matbee-eth I think I've understood your issue wrong, didn't I? Did you mean the package `@odata2ts/axios-odata-client` itself an it's current dependency on the outdated `axios@0.27.x`?

I'll change `axios` to become a peer dependency as you suggest.

**Comment by texttechne** [comment]
Completely refactored all http clients and moved them to another repo: https://github.com/odata2ts/http-client
There are 3 clients available now:
* Axios: `@odata2ts/http-client-axios`
* JQuery: `@odata2ts/http-client-jquery`
* Fetch: `@odata2ts/http-client-fetch`

In the course of this excercise
* @matbee-eth Axios became a peer-dependency, which solves the intial request
* @manuelseeger most instance variables and methods are `protected` instead of `private` in order to allow overriding them when extending the client
