### ISSUE TITLE
[Feature Request] generated types also for the Entity Container

### ISSUE THREAD

**Issue by heimwege** [odata2ts/odata2ts#230]
Might be a very special use case but how about generating a type for the EntityContainer of the metadata document as well? Currently only types for the EntitySets of that container are being generated.

Use Case: [ui5 middleware mockserver](https://www.npmjs.com/package/@sap-ux/ui5-middleware-fe-mockserver) supports extending the mockserver (e.g. to mock ActionImports). In case of a bound action it is part of the respective entity set and I can use the odata2ts generated types of that entity set. In case of an unbound action, this action is part of the EntityContainer. Currently I'm missing the correct (odata2ts generated) type of that EntityContainer to be used in my mockserver extension and therefore create the type manually

```
import {EntitySetA} from "../../ext/types/gen/MyServiceModel";
import {EntitySetB} from "../../ext/types/gen/MyServiceModel";
import {EntitySetC} from "../../ext/types/gen/MyServiceModel";

type EntityContainer = {
    EntitySetA: EntitySetA,
    EntitySetB: EntitySetB,
    EntitySetC: EntitySetC
}
```

What do you think?

**Comment by texttechne** [comment]
Hi @heimwege,

Since you're talking about ActionImports I assume that you're confronted with OData V4. I further assume that you're only generating models, not the full OData client. 

Based on these assumptions I'm unsure what you're missing, because odata2ts generates types for the parameters of the actions & functions it finds in the EDMX document. The `ActionImport` element only references a certain `Action` type and for this type you'll get a TS interface representing the parameters. If there are no parameters there will be no generated interface, of course...

The entity container itself can be regarded as the real API of the OData service in question. If you're only generating models it's not relevant at all. When generating the full OData client, then the OData client relies on the information of the EntityContainer to represent this API.  It's more or less backed into the client. But having types for the EntityContainer makes no sense to me.

I'm also using the MockServer (I actually love it). Typing can help when you're mocking any kind of Action or Function - may they be bound or not. Here you would have something like:
```
this.base.getEntityInterface("People") as Array<Person>
```
I don't see how you would get around this type casting or how an EntityContainer type would help here....

Where odata2ts would really shine is when retrieving the parameters out of the URL. You would need to generate `qobjects` instead of `models` and then can parse the URL to retrieve the parameters as object. Along these lines:
```
const params: GetNearestAirportParamsModel = new QGetNearestAirport().parseUrl(myUrl);
```

These are my 2 cents regarding the topic of the MockServer. However, I'm really unsure if that answers your question at all or what kind of intention you have when asking for types of the EntityContainer.

**Comment by heimwege** [comment]
Hey @texttechne,

sorry for providing too less information and the type/set confusion 🙈 Seems like my brain was already out for lunch last friday 😹 You are of course right with odata v4 and only usage of generated types.

Context:
I did some mockserver extensions in js and struggled with the convertion to ts because of (or better: I did not like the) too unspecific types. So I [contributes to the mockserver](https://github.com/SAP/open-ux-odata/pull/497) that it better supports types:

```
import type {MockDataContributor} from "@sap-ux/ui5-middleware-fe-mockserver";
```

` MockDataContributor` changed to ` MockDataContributor<object>`.

Which also means that you MUST provide an object. In case of an entity I can use the odata2ts generated types

`const mockDataContributor: MockDataContributor<EntitySetA> = {`

Now I added an extension to handle an unbound action for the first time and noticed that in case of the `EntityContainer` (mockserver enhancement needs to be called EntityContainer.js/.ts) there exists no odata2ts generated type of the container as such. That's why I did

```
import type {MockDataContributor} from "@sap-ux/ui5-middleware-fe-mockserver";
import {EntityTypeA} from "../../ext/types/gen/MyServiceModel";
import {EntityTypeB} from "../../ext/types/gen/MyServiceModel";
import {EntityTypeC} from "../../ext/types/gen/MyServiceModel";

type EntityContainer = {
    EntityTypeA: Array<EntityTypeA>,
    EntityTypeB: Array<EntityTypeB>,
    EntityTypeC: Array<EntityTypeC>
}

const mockDataContributor: MockDataContributor<EntityContainer> = {
    executeAction: async function (actionDefinition, actionData: never, keys, odataRequest) {
        [...]
    }
}
```

That works perfectly fine. In my specific sample I don't even use the provided type (that why I didn't even notice the missing `Array`) because I only implemented the handling of the unbound action of the mockserver 🙈  But as said the type must be provided for the extension in ts. And that's where I thought maybe it would make sense if this is generated as well.
But I also agree that this might be a very specific use case (that does not even exist at all outside the context of the sap-fe-mockserver) and it's not worth the effort.

**Comment by texttechne** [comment]
Hi @heimwege,

still, this doesn't seem to add up. The `MockDataContributor` interface is about one specific `EntitySet` and the generics you introduced (kudos!) are about a specific `EntityType`. `addEntry` for example represents the create / post method of an `EntitySet`, so you feed it with exactly one object of the appropriate `EntityType`...

`MockDataContributor<EntityContainer>` makes no sense as `createEntry` would now state that you need to pass an EntityContainer type instead of the `EntityType`.... I hope you see the mistake there...

I'm actually a big fan of UI5's mock server. Here are the use cases I can envision for odata2ts:
* obviously using the generated types 😄 
* parsing the URL parameters of a custom action / function 
  * quite trivial in V4: strings are surrounded by single quotes everything else is literal
  * quite complex in V2: number suffixes, data type prefixes, ...
* data type conversion
  * this would support advanced data manipulation, e.g. date manipulations
  * seems to be a rare use case....

**Comment by heimwege** [comment]
I can totally understand/share your confusion 😄 

In terms of mockserver extensions a mock for a bound action is the implementation of the `executeAction` method for a .js file that is named exactly as the .json file including the mockdata. Using the name of the respective EntitySet the action/mockdata belongs to.

`MyEntity.js` <-- transpiled via babel from ts and picked up by the mockserver at start
`MyEntity.ts` <-- actual implementation
`MyEntity.json` <-- mockdata for MyEntity

For an unbound action that is not related to any EntitySet the solution form a mockserver point of view is to name the file `EntityContainer.js` and implement the `executeAction` method there. With this all unbound actions can be mocked.

`EntityContainer.js` <-- transpiled via babel from ts and picked up by the mockserver at start
`EntityContainer.ts` <-- actual implementation
~~`EntityContainer.json`~~ <-- does not exist: mockdata makes no sense here

And this brings us back to the `MockDataContributor` demanding a type for its implementation. In case of a bound action the type is the EntityType. Now the question is what to do in case of an unbound action? My solution was the above mentioned dummy type for the EntityContainer.

It might be that this whole concept is in general a bit odd from a mockserver concept pov because the other callbacks besides the `executeAction` of this mockdatacontributor will never be taken into account in case of `EntityContainer.js` because as you said there will never be a create or update entity.

**Comment by texttechne** [comment]
Hi @heimwege,

ah ok, the `MockDataContributor` is also reused for unbound operations. One could argue that this interface is misused here, because only a subset of it is valid in case of defining unbound operations...

In any case, you don't gain anything by a more or less correct typing there, because it doesn't help you with the only function you need to implement: `executeAction`. So you could also use just `{}`, right?

From the standpoint of odata2ts, it really doesn't make sense to generate a type for the EntityContainer...

**Comment by heimwege** [comment]
Hm. Actually your are right. I did not even think about simply using an empty type. Sometimes it's as easy as that 🙈
