### ISSUE TITLE
load component issue with Odata V2

### ISSUE THREAD

**Issue by yavuzasik** [odata2ts/odata2ts#234]
Hi ,
I get the following error in my console during an OdataV2 service implementation. I wanted to setup a JQuery client to my sapui5 app , however it never loads the relevant libraries to the resources during the initial load. It is valid for all modules under the odata2ts actually. I believe all the settings and installations are in-line with the documentation. Does anyone have an idea about what could the possible cause be for this unsuccessful loading? 

"Failed to load component for container container. Reason: Error: failed to load '@odata2ts/http-client-jquery.js' from resources/@odata2ts/http-client-jquery.js: script load error - "

Thanks
Yavuz

**Comment by texttechne** [comment]
Hi @yavuzasik,

so you want to generate the full odata client for usage in UI5 and you're confronted with V2.
Very cool, that you provided that info. It needs to go in an issue template 😅 

Use this as your example project: [https://github.com/odata2ts/playground/tree/main/packages/ui5-mobx](https://github.com/odata2ts/playground/tree/main/packages/ui5-mobx)

Some hints / tipps:
* make sure that you install `ui5-tooling-modules` in order to support packages consumed via NPM
* pay extra attention to the `ui5.yaml` which configures this stuff...
* also note the wiring in `tsconfig.json`

Otherwise I need more info. Can you provide an example project?

**Comment by yavuzasik** [comment]
Hi @texttechne 
Thanks for your swift reply. I actually followed the steps in the documentation and at the same time compared it with the playground example. Indeed playground example works perfect in my local as well.  The only differences between my project and sample project seems to be different versions of odata2ts modules. You can see the project in the below repo. Thanks..

https://github.com/yavuzasik/logon_service

**Comment by yavuzasik** [comment]
Hi @texttechne 
I could make it work indeed with your last tips. However ui5-tooling-modules part is really something I really missed in the documentation. Maybe it would be useful to emphasize that somewhere in the document because it is an addon which is not used by default within an ordinary ui5 project . 
Thanks again for the support.
cheers
Yavuz
