### ISSUE TITLE
[odata-uri-builder] Support advanced search format

### ISSUE THREAD

**Issue by merlosy** [odata2ts/odata2ts#74]
# Feature request

Hi!
I might have skipped something and it might be there, but there seem to be missing advanced `$search` query API for odata v4.
Here is an example from the spec: http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionsearch

Detail on formating: https://docs.oasis-open.org/odata/odata/v4.01/os/abnf/odata-abnf-construction-rules.txt

It would be a nice addition

**Comment by texttechne** [comment]
Hey,
this feature has been implemented, but only in a simple form.
Since it's a V4 feature it's only to be found on the `ODataUriBuilderV4` as method `search`.
Feature matrix:
* single term: supported
* sinlge phrase: supported
* multiple terms or phrases: not supported
* logical operators: not supported

Here are [the tests](https://github.com/odata2ts/odata2ts/blob/main/packages/odata-uri-builder/test/ODataUriBuilderV4.test.ts#L149).

Is this sufficient for you?

**Comment by merlosy** [comment]
Hi!

We need to support multiple terms like "term1 term2" together, and also "term1" OR "term2", and combinaison of those.

Thanks

**Comment by texttechne** [comment]
Hi @merlosy,

the advanced search format is now fully supported.
To get operators you need a `QSearchTerm`. A factory function called `searchTerm` should be used for that:

```ts
import { searchTerm } from "@odata2ts/odata-query-objects";

...
builder.search(searchTerm("test").or("my phrase"))
```

The search function as well as the factory function or any operator value allows for `null` and `undefined` to signal no value.
Passing strings instead of QSearchTerm objects will evaluate if this is a phrase (surrounded by double quotes) or only a single term.

**Comment by texttechne** [comment]
Impolitely closed this ticket prematurely.
